version: '3.7'

services:
  postgres-speedroute:
    container_name: postgres-speedroute
    image: postgres:bullseye
    ports:
    - "5432:5432"
    restart: unless-stopped
    environment:
      POSTGRES_USER: speedroute
      POSTGRES_PASSWORD: speedroute
      POSTGRES_DB: speedroute

  adminer:
    container_name: adminer
    image: adminer
    restart: unless-stopped
    environment:
      ADMINER_DEFAULT_SERVER: postgres-speedroute
    ports:
      - 8080:8080

networks:
  default:
